### PR TITLE
Feature/use env variables

### PR DESCRIPTION
**Pull request by fossum**
Moving from hard-coded values in the demo script to environment variables which can be loaded from a dot-env file.

### CODE REVIEW

**Review by denisemauldin — APPROVED** [review]

**Comment by fossum** [comment]
I'm not sure what the PR process is for this repo, but I don't have permissions to merge. Are we waiting on others before merging this in?

**Comment by denisemauldin** [comment]
@daroot Do you have merge permissions or can you give them to me?

**Comment by daroot** [comment]
I do not have write perms to the flowroute org anymore, which is necessary for merging.   https://github.com/flowroute doesn't even show any public members.  You'll need to find who currently owns that org.

**Comment by denisemauldin** [comment]
@hjhixon @alextotheroh Do either of you have write permissions?

**Comment by denisemauldin** [comment]
Thanks @clacina !

**Pull request merged**
